/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch.teko;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;


// public class App {
//     public String getGreeting() {
//         return "Hello world.";
//     }

//     public static void main(String[] args) {
//         System.out.println(new App().getGreeting());
//     }
// }


public class App extends Application{

    public static void main(String[] args) {
        launch(args);
    }

    public void start(Stage primaryStage){
        primaryStage.setTitle("JavaFX Test");
        Label label = new Label("Hello JavaFX World!");

        StackPane stack_pane = new StackPane();
        stack_pane.getChildren().add(label);
        Scene scene = new Scene(stack_pane, 400, 400);

        primaryStage.setScene(scene);
        primaryStage.show();
    }
}
